package syncer

import (
	"fmt"
	"path/filepath"
	"slices"
	"strings"

	"github.com/wpt/b00p/pkg/fileutil"
	"github.com/wpt/b00p/pkg/state"
)

// blogIndexName is the navigation index written at the blog root. An archive
// grows into hundreds of directories; the index gives the user one file to
// scan (and click through) instead of a raw directory listing. It is
// regenerated wholesale from state on every completed run, so it needs no
// incremental bookkeeping and self-heals if deleted.
const blogIndexName = "index.md"

// renderBlogIndex builds the index.md content from state entries. Entries
// are sorted by DirName — the default {date}_{title} format makes that
// chronological — with the post ID as a deterministic tie-break. Pure
// function for table tests.
func renderBlogIndex(blog string, posts map[string]state.PostEntry) string {
	type row struct {
		id string
		e  state.PostEntry
	}
	rows := make([]row, 0, len(posts))
	locked := 0
	for id, e := range posts {
		rows = append(rows, row{id, e})
		if e.Locked {
			locked++
		}
	}
	slices.SortFunc(rows, func(a, b row) int {
		if c := strings.Compare(a.e.DirName, b.e.DirName); c != 0 {
			return c
		}
		return strings.Compare(a.id, b.id)
	})

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — archive index\n\n", blog)
	fmt.Fprintf(&b, "%d post(s)", len(rows))
	if locked > 0 {
		fmt.Fprintf(&b, " (%d locked)", locked)
	}
	b.WriteString(". Auto-generated by b00p from `_state.json` on every run — do not edit.\n\n")

	// Titles can contain markdown link syntax; escape backslashes and
	// brackets so a title like "[draft] stream" or one with a trailing
	// backslash cannot break the link structure. Backslash must be in the
	// same Replacer (replacements don't cascade), listed for clarity first.
	escaper := strings.NewReplacer(`\`, `\\`, "[", `\[`, "]", `\]`)
	for _, r := range rows {
		// Angle-bracket destination: CommonMark-safe for directory names
		// containing spaces. SanitizeTitle strips < and > from titles, so
		// the name cannot terminate the brackets early.
		fmt.Fprintf(&b, "- [%s](<./%s/>)", escaper.Replace(r.e.Title), r.e.DirName)
		if r.e.HasComments {
			fmt.Fprintf(&b, " — %d comment(s)", r.e.CommentsCount)
		}
		if r.e.Locked {
			b.WriteString(" (locked)")
		}
		b.WriteString("\n")
	}
	return b.String()
}

// writeBlogIndex regenerates index.md in blogDir from the current state.
// Skipped when state tracks nothing — don't drop artefacts into a directory
// for a blog with no downloaded posts. Failures are logged, never fatal:
// the index is a convenience artefact derived from state, not data, and the
// next run rewrites it.
func (e *Engine) writeBlogIndex(blogDir string, st *state.State) {
	e.stMu.Lock()
	var content string
	if len(st.Posts) > 0 {
		content = renderBlogIndex(e.cfg.Blog, st.Posts)
	}
	e.stMu.Unlock()
	if content == "" {
		return
	}
	if err := fileutil.WriteFileAtomic(filepath.Join(blogDir, blogIndexName), []byte(content), 0644); err != nil {
		e.c.Log.Printf("  warning: failed to write %s: %v", blogIndexName, err)
	}
}
